stock
edisonrmedina/Cava-Ecommerce pull request #120
Opened 2023-08-03 00:24 UTC by Julivito22

2023-08-03 04:18 UTC, Fr4nco77 approved these changes

2023-08-03 15:26 UTC, ahlaulhee requested changes
Falta limitar la cantidad del producto en el input al stock disponible

2023-08-05 23:14 UTC, Fr4nco77 requested changes
El atributo "isActive" es importante, si lo comentas habrá varios errores

2023-08-06 01:06 UTC, Fr4nco77 approved these changes

2023-08-06 13:34 UTC, ahlaulhee approved these changes

2023-08-06 15:09 UTC, merged